---
# - name: os-specific vars
#   include_vars: "{{ ansible_os_family }}.yml"

- name: "Install java"
  include: java.yml
  when: springboot_java_install

- name: "Create group for springboot app"
  group:
    name: "{{ springboot_group }}"
    state: present

- name: "Create user for springboot app"
  user:
    name: "{{ springboot_user }}"
    group: "{{ springboot_group }}"
    state: present

- name: "Install springboot"
  include: springboot.yml

