---
- hosts: "{{ hostgroup | default('base') }}"
  become: true
  any_errors_fatal: true
  remote_user: root
  become_user: root
  tasks:
  - name: Download Config YAML
    #  --filename: 需要下载的文件，--saveas：文件下载后保存的路径
    ansible.builtin.command: /tmp/scripts/myscript --filename config.yaml-202311201846452768 --saveas /tmp/scripts/config1.yaml
