---
#  - name: Install Application - nginx redis nacos
#    hosts: "{{ hostgroup | default('application') }}"
#    become: true
#    any_errors_fatal: true
#    remote_user: root
#    become_user: root
#    roles:
#     - nginx_install
#     - redis_install
#     - nacos_install

 - name: Install Application - application
   hosts: "{{ hostgroup | default('springboot') }}"
   become: true
   any_errors_fatal: true
   remote_user: root
   become_user: root
   roles:
    - springboot_install