---
- name: Database Server Database Creation
  hosts: "{{ hostgroup | default('oracle') }}"
  become: true
  any_errors_fatal: true
  roles:
    - oradb_manage_db
    - oradb_manage_pdb
    - oradb_manage_parameters
    - oradb_manage_tablespace
    - oradb_manage_redo
    - oradb_manage_profiles
    - oradb_manage_statspack
    - oradb_manage_roles
    - oradb_manage_users
    - oradb_manage_grants
    - oradb_manage_services
    - oradb_rman
