- name: Copy SSH Public key 
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  remote_user: root
  become_user: root
  tasks:
  - name: Set authorized key took from file
    authorized_key: 
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
      user: root
      state: present