# cxoracle-install playbook
---
- name: Install cx_oracle
  ansible.builtin.pip:
     name: "{{ cx_oracle_source | default('cx_oracle<8.0') }}"
     extra_args: "{{ extra_args }}"
     umask: "{{ cx_oracle_umask | default(omit) }}"
     state: present
  when: install_cx_oracle
  tags: cx_oracle
