packages_dir: /root/softwares/middleware
nginx_package: nginx-1.23.4
common_packages:
  "{% if ansible_distribution_major_version | int == 6 %}{{ common_packages_el6 }}\
  {%- elif ansible_distribution_major_version | int == 7 %}{{ common_packages_el7 }}\
  {%- elif ansible_distribution_major_version | int == 8 %}{{ common_packages_el8 }}\
  {%- else %}None\
  {%- endif %}"
common_packages_el6:
  - make
  - gcc 
  - gcc-c++
  - pcre 
  - pcre-devel
  - zlib 
  - zlib-devel
  - openssl 
  - openssl-devel
common_packages_el7:
  - make
  - gcc 
  - gcc-c++
  - pcre 
  - pcre-devel
  - zlib 
  - zlib-devel
  - openssl 
  - openssl-devel
common_packages_el8:
  - make
  - gcc 
  - gcc-c++
  - pcre 
  - pcre-devel
  - zlib 
  - zlib-devel
  - openssl 
  - openssl-devel
nginx_home: /glzt/nginx
nginx_modules: "--with-http_ssl_module --with-http_stub_status_module"
nginx_www: "{{ nginx_home }}/html"

# nginx 配置文件相关
# C端
domain_name: demo.gih.cn # 修改成指定域名
ssl_cert: "{{domain_name}}.pem" # 申请的 SSL 证书
ssl_key: "{{domain_name}}.key" # 申请的 SSL 证书私钥
api_proxy: http://proxy.gih.cn:8082/ # 机构前置机代理




