packages_dir: /root/softwares/nginx
nginx_package: nginx-1.23.3
common_packages:
  "{% if ansible_distribution_major_version | int == 6 %}{{ common_packages_el6 }}\
  {%- elif ansible_distribution_major_version | int == 7 %}{{ common_packages_el7 }}\
  {%- elif ansible_distribution_major_version | int == 8 %}{{ common_packages_el8 }}\
  {%- else %}None\
  {%- endif %}"
common_packages_el6:
  - make
  - gcc 
  - gcc-c++
  - pcre 
  - pcre-devel
  - zlib 
  - zlib-devel
  - openssl 
  - openssl-devel
common_packages_el7:
  - make
  - gcc 
  - gcc-c++
  - pcre 
  - pcre-devel
  - zlib 
  - zlib-devel
  - openssl 
  - openssl-devel
common_packages_el8:
  - make
  - gcc 
  - gcc-c++
  - pcre 
  - pcre-devel
  - zlib 
  - zlib-devel
  - openssl 
  - openssl-devel
nginx_home: /opt/nginx
nginx_modules: "--with-http_ssl_module --with-http_stub_status_module"
nginx_www: /var/www/html

# nginx 配置文件相关
# C端
domain_name: 192.168.3.216
ssl_cert: demo.pem
ssl_key: demo.key
api_proxy: http://xxxx:8082/




