---
all:
  children:
    base:
      hosts:
        192.168.110.93:
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_port: 22
        192.168.110.94:
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_port: 22
        192.168.110.95:
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_port: 22
    security:
      hosts:
        192.168.79.132:
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_port: 22
    mysql:
      hosts:
        192.168.79.134:
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_port: 22
        192.168.79.135:
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_port: 22
        192.168.79.136:
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_port: 22
    middleware:
      hosts:
        192.168.110.95:
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_port: 22
    backend:
      hosts:
        192.168.79.132:
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_port: 22
    # oracle:
    #   hosts:
    #     oracle18.db:
    #       ansible_connection: ssh
    #       ansible_ssh_user: root
    #       ansible_ssh_port: 22
