---
all:
  children:
    mysql:
      hosts:
        mysql57.db:
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_port: 22
    # oracle:
    #   hosts:
    #     oracle18.db:
    #       ansible_connection: ssh
    #       ansible_ssh_user: root
    #       ansible_ssh_port: 22
    middleware:
      hosts:
        app.mw:
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_port: 22
    backend:
      hosts:
        app.back:
          ansible_connection: ssh
          ansible_ssh_user: root
          ansible_ssh_port: 22
