---
 - name: stransfer sql to remote host
   ansible.builtin.template: 
    src: master_slaves.sql
    dest: /tmp/master_slaves.sql

 - name: create replication user on master / start slave on slave
   when:
   ansible.builtin.shell: "{{ mysql_base_dir }}/bin/mysql -hlocalhost -uroot -S /tmp/mysql.sock < /tmp/master_slaves.sql -p{{ mysql_root_password }}"

 - name: clear temp file /tmp/master_slaves.sql
   ansible.builtin.file:
    dest: /tmp/master_slaves.sql
    state: absent
