- name: create systemd config file
  when: ansible_distribution_major_version == "7"
  ansible.builtin.template:
    src: mysql.service
    dest: /usr/lib/systemd/system/mysql.service

- name: start mysql(sytemctl)
  when: ansible_distribution_major_version == "7"
  ansible.builtin.systemd:
    name: mysql
    state: started
    daemon_reload: yes

- name: config mysql.service start up on boot
  when: ansible_distribution_major_version == "7"
  ansible.builtin.systemd:
    name: mysql
    enabled: yes
    daemon_reload: yes

- name: config sysv start script
  when: ansible_distribution_major_version == "6"
  ansible.builtin.copy:
    remote_src: yes
    src: "{{mysql_base_dir + 'support-files/mysql.server'}}"
    dest: /etc/init.d/mysqld
    mode: 0755

- name: start mysql(service)
  when: ansible_distribution_major_version == "6"
  ansible.builtin.service:
    name: mysqld
    state: started

- name: config mysql.service start up on boot
  when: ansible_distribution_major_version == "6"
  ansible.builtin.shell: chkconfig mysqld on
