---
 - name: transfer sql to remonte host
   ansible.builtin.template: 
    src: ../template/config_multi_source_replication.sql
    dest: /tmp/config_mutli_source_replication.sql

 - name: create multi source replication user on master / start slave on slave
   when:
   ansible.builtin.shell: mysql -hlocalhost -uroot -p{{ mysql_root_password }} -S /tmp/mysql.sock  < /tmp/config_mutli_source_replication.sql

 - name: clear temp file /tmp/config_mutli_source_replication.sql
   ansible.builtin.file:
    dest: /tmp/config_mutli_source_replication.sql
    state: absent
