---
 - hosts: mgrstudio
   vars_files:
    - ../../../config.yml
    - ./vars/group_replication.yml
  
   tasks:
    - name: create user and config file
      import_tasks: common/create_user_and_config_file.yml

    - name: install mysql dependents 
      import_tasks: common/install_mysql_dependents.yml

    - name: install mysql
      import_tasks: common/install_mysql.yml

    - name: init mysql datadir
      import_tasks: common/initialize_mysql_datadir.yml

    - name: config mysql service and start mysql
      import_tasks: common/config_mysql_service_and_start_mysql.yml

    - name: sleep 15 seconds
      import_tasks: ./common/sleep_15.yml

    - name: make mysql secure
      import_tasks: common/make_mysql_security.yml

    - name: config mysql group replication 
      import_tasks: common/config_mgr.yml


