---
- name: create user and config file
  ansible.builtin.include_tasks: create_user_and_config_file.yml

- name: install mysql dependents 
  ansible.builtin.include_tasks: install_mysql_dependents.yml

- name: install mysql to /usr/local/mysql
  ansible.builtin.include_tasks: install_mysql.yml

- name: init mysql datadir
  ansible.builtin.include_tasks: initialize_mysql_datadir.yml

- name: config mysql service and start mysql
  ansible.builtin.include_tasks: config_mysql_service_and_start_mysql.yml

- name: sleep 15's
  ansible.builtin.shell: sleep 15

- name: make mysql secure
  ansible.builtin.include_tasks: make_mysql_security.yml

- name: import database
  ansible.builtin.include_tasks: import_data_struct.yml
  when: import_data_struct == 1

- name: config replication
  ansible.builtin.import_tasks: config_master_slaves.yml