- name: transfer sql statement to remonte
  when: mtls_make_mysql_secure == 1
  ansible.builtin.template:
    src: secure.sql
    dest: /tmp/make_mysql_secure.sql

- name: make mysql secure
  when: mtls_make_mysql_secure == 1
  ansible.builtin.shell: mysql -hlocalhost -uroot -S /tmp/mysql.sock < /tmp/make_mysql_secure.sql

- name: remove temp file /tmp/make_mysql_secure.sql
  ansible.builtin.file:
    dest: /tmp/make_mysql_secure.sql
    state: absent
