---
 - name: transfer sleep script to /tmp/
   ansible.builtin.copy:
    src: sleep_15.sh
    dest: /tmp/sleep_15.sh

 - name: sleep 15 seconds
   ansible.builtin.shell: bash /tmp/sleep_15.sh

 - name: remove /tmp/sleep_15.sh
   ansible.builtin.file:
    dest: /tmp/sleep_15.sh
    state: absent

   