---
# defaults file for host-config-ssh
hostgroup: "{{ group_names[0] }}"
role_separation: false
oracle_group: oinstall                          # Primary group for oracle_user.
oracle_user: oracle
grid_user: grid
oracle_users:         # Passwd :Oracle123
  - {username: oracle, primgroup: oinstall}
  - {username: grid, primgroup: oinstall}
