---
# Install java by default. Optional
springboot_java_install: false

springboot_applications:
  - { deploy_folder: '/opt/record', src_file: '/root/softwares/application/Record-1.0.0-SNAPSHOT.jar', application_name: 'Record-1.0.0-SNAPSHOT.jar', configuration_template: false, startup: 'startup.sh' }

springboot_group: springboot
springboot_user: springboot
