---
# Install java by default. Optional
springboot_java_install: true
springboot_java_home: /usr/lib/jvm/jre-openjdk # /usr/lib/jvm/jre-openjdk, if springboot_java_install == true

# User and Group
springboot_group: springboot
springboot_user: springboot

# Nacos
springboot_nacos: 
  url: "localhost:8848" # 指定 Nacos 地址，默认为：localhost:8848
  namespace: "GoBroad" # 指定 命名空间，默认为：public
  user: "nacos" # 指定 用户名，默认为：nacos
  password: "nacos" # 指定 密码，默认为：nacos

# Backends
springboot_applications: # 有多少个服务加多少 application
- app_short_name: 'AdminService'
  app_long_name: 'AdminService'
  deploy_folder: '/glzt/PatientService/AdminService'
  app_bin: 'AdminService.jar' 
  src_file: '/root/softwares/application/AdminService.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'PortalService'
  app_long_name: 'PortalService'
  deploy_folder: '/glzt/PatientService/PortalService'
  app_bin: 'PortalService.jar' 
  src_file: '/root/softwares/application/PortalService.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'GatewayService'
  app_long_name: 'GatewayService'
  deploy_folder: '/glzt/PatientService/GatewayService'
  app_bin: 'GatewayService.jar' 
  src_file: '/root/softwares/application/GatewayService.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'CaAgentService'
  app_long_name: 'CaAgentService'
  deploy_folder: '/glzt/PatientService/CaAgentService'
  app_bin: 'CaAgentService.jar' 
  src_file: '/root/softwares/application/CaAgentService.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'DoctorService'
  app_long_name: 'DoctorService'
  deploy_folder: '/glzt/PatientService/DoctorService'
  app_bin: 'DoctorService.jar' 
  src_file: '/root/softwares/application/DoctorService.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'JobExecutor'
  app_long_name: 'JobExecutor'
  deploy_folder: '/glzt/PatientService/JobExecutor'
  app_bin: 'JobExecutor.jar' 
  src_file: '/root/softwares/application/JobExecutor.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'MAppointReg'
  app_long_name: 'MAppointReg'
  deploy_folder: '/glzt/PatientService/MAppointReg'
  app_bin: 'MAppointReg.jar' 
  src_file: '/root/softwares/application/MAppointReg.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'PrintManage'
  app_long_name: 'PrintManage'
  deploy_folder: '/glzt/PatientService/PrintManage'
  app_bin: 'PrintManage.jar' 
  src_file: '/root/softwares/application/PrintManage.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'SpringbootAdmin'
  app_long_name: 'SpringbootAdmin'
  deploy_folder: '/glzt/PatientService/SpringbootAdmin'
  app_bin: 'SpringbootAdmin.jar' 
  src_file: '/root/softwares/application/SpringbootAdmin.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'Chat'
  app_long_name: 'Chat'
  deploy_folder: '/glzt/PatientService/Chat'
  app_bin: 'Chat.jar' 
  src_file: '/root/softwares/application/Chat.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'CRFManager'
  app_long_name: 'CRFManager'
  deploy_folder: '/glzt/PatientService/CustomForm'
  app_bin: 'CRFManager.jar' 
  src_file: '/root/softwares/application/CRFManager.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'gaobopayment'
  app_long_name: 'gaobopayment'
  deploy_folder: '/glzt/PatientService/gaobopayment'
  app_bin: 'gaobopayment.jar' 
  src_file: '/root/softwares/application/gaobopayment.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'HisAdapterService'
  app_long_name: 'HisAdapterService'
  deploy_folder: '/glzt/PatientService/HisAdapterService'
  app_bin: 'HisAdapterService.jar' 
  src_file: '/root/softwares/application/HisAdapterService.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'JobAdmin'
  app_long_name: 'JobAdmin'
  deploy_folder: '/glzt/PatientService/JobAdmin'
  app_bin: 'JobAdmin.jar' 
  src_file: '/root/softwares/application/JobAdmin.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'MDTService'
  app_long_name: 'MDTService'
  deploy_folder: '/glzt/PatientService/MDTService'
  app_bin: 'MDTService.jar' 
  src_file: '/root/softwares/application/MDTService.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'Task'
  app_long_name: 'Task'
  deploy_folder: '/glzt/PatientService/TaskService'
  app_bin: 'Task.jar' 
  src_file: '/root/softwares/application/Task.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'usermanage'
  app_long_name: 'usermanage-1.0.0-SNAPSHOT'
  deploy_folder: '/glzt/PatientService/UserManage'
  app_bin: 'usermanage-1.0.0-SNAPSHOT.jar' 
  src_file: '/root/softwares/application/usermanage-1.0.0-SNAPSHOT.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
- app_short_name: 'UserService'
  app_long_name: 'UserService'
  deploy_folder: '/glzt/PatientService/UserService'
  app_bin: 'UserService' 
  src_file: '/root/softwares/application/UserService.jar'
  configuration_template: false
  startup: 'startup.sh'
  jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数

# # Backends
# springboot_applications: # 有多少个服务加多少 application
# - app_short_name: 'Appoint'
#   app_long_name: 'Appoint'
#   deploy_folder: '/glzt/his_new/appoint'
#   app_bin: 'appoint-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/appoint-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
# - app_short_name: 'MedInsurance'
#   app_long_name: 'MedInsurance'
#   deploy_folder: '/glzt/his_new/finance/medinsurance'
#   app_bin: 'medinsurance-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/medinsurance-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
# - app_short_name: 'HispRes'
#   app_long_name: 'HispRes'
#   deploy_folder: '/glzt/his_new/hisp_resource'
#   app_bin: 'hispresource-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/hispresource-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
# - app_short_name: 'FileManage'
#   app_long_name: 'FileManage'
#   deploy_folder: '/glzt/his_new/file_manage'
#   app_bin: 'filemanage-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/filemanage-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
# - app_short_name: 'Schedule'
#   app_long_name: 'Schedule'
#   deploy_folder: '/glzt/his_new/schedule'
#   app_bin: 'schedule-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/schedule-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
# - app_short_name: 'SocketServer'
#   app_long_name: 'SocketServer'
#   deploy_folder: '/glzt/his_new/socketserver'
#   app_bin: 'socketserver-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/socketserver-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
# - app_short_name: 'PrintManage'
#   app_long_name: 'PrintManage'
#   deploy_folder: '/glzt/his_new/print_manage'
#   app_bin: 'printManage-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/printManage-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
# - app_short_name: 'Task'
#   app_long_name: 'Task'
#   deploy_folder: '/glzt/his_new/task'
#   app_bin: 'task-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/task-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
# - app_short_name: 'zuul-gateway'
#   app_long_name: 'zuul-gateway'
#   deploy_folder: '/glzt/his_new/gate_way'
#   app_bin: 'Gateway-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/Gateway-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数
# - app_short_name: 'OrgManage'
#   app_long_name: 'OrgManage'
#   deploy_folder: '/glzt/his_new/org_manager'
#   app_bin: 'orgmanage-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/orgmanage-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数

# - app_short_name: 'TemplateEngine'
#   app_long_name: 'TemplateEngine'
#   deploy_folder: '/glzt/his_new/template_engine'
#   app_bin: 'templateEngine-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/templateEngine-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数

# - app_short_name: 'Register'
#   app_long_name: 'Register'
#   deploy_folder: '/glzt/his_new/register'
#   app_bin: 'register-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/register-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数

# - app_short_name: 'BaseService'
#   app_long_name: 'BaseService'
#   deploy_folder: '/glzt/his_new/baseservice'
#   app_bin: 'basespringboot-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/basespringboot-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数

# - app_short_name: 'DictManage'
#   app_long_name: 'DictManage'
#   deploy_folder: '/glzt/his_new/dict_manage'
#   app_bin: 'dictmanage-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/dictmanage-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数

# - app_short_name: 'UserManage'
#   app_long_name: 'UserManage'
#   deploy_folder: '/glzt/his_new/user_manager'
#   app_bin: 'usermanage-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/usermanage-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数

# - app_short_name: 'OutpatientDoctor'
#   app_long_name: 'OutpatientDoctor'
#   deploy_folder: '/glzt/his_new/outp_doctor'
#   app_bin: 'outpdoctor-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/outpdoctor-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数

# - app_short_name: 'HisAdapter'
#   app_long_name: 'HisAdapter'
#   deploy_folder: '/glzt/his_new/hisadapter'
#   app_bin: 'hisadapter-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/hisadapter-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数

# - app_short_name: 'emrservice'
#   app_long_name: 'emrservice'
#   deploy_folder: '/glzt/his_new/emrservice'
#   app_bin: 'emrspringboot-1.0.0.jar' 
#   src_file: '/root/softwares/application/B/emrspringboot-1.0.0.jar'
#   configuration_template: false
#   startup: 'startup.sh'
#   jvm_opt: "-XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=1024m -Xms256m -Xmx256m" # 指定 JVM 参数