---
galaxy_info:
  role_name: orahost
  author: Mikael Sandström
  description: orahost role from ansible-oracle.
  company: Mikael Sandström

  license: license (MIT)

  min_ansible_version: 2.9.0

  platforms:
    - name: EL
      versions:
        - "6"
        - "7"
        - "8"

  galaxy_tags: []

dependencies:
  - role: orahost_meta
