---
- name: Install Nacos - Install JDK
  ansible.builtin.include: java.yml
  when: java_install

- name: Inatall Nacos - Install unzip
  yum:
    name: unzip
    state: "present"
    update_cache: yes
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Anolis OS' or ansible_os_family == 'OracleLinux'


- name: Install Nacos - unzip Nacos zip
  ansible.builtin.unarchive:
    src: "{{packages_dir}}/{{nacos_package}}"
    dest: "{{nacos_basedir}}/"
    #remote_src: yes

# - name: Install Nacos - Start Nacos
#   ansible.builtin.command: sh {{nacos_home}}/bin/startup.sh -m standalone

- name: Install Nacos - Copy startup.sh
  ansible.builtin.template:
    src: startup.sh.j2
    dest: "{{nacos_home}}/bin/startup.sh"
    owner: root
    group: root
    mode: u=rwx,g=r,o=r

- name: Install Nacos - Copy application.properties
  ansible.builtin.template:
    src: application.properties.j2
    dest: "{{nacos_home}}/conf/application.properties"
    owner: root
    group: root
    mode: u=rwx,g=r,o=r

- name: Install Nacos - Copy nacos.service
  ansible.builtin.template:
    src: nacos.service.j2
    dest: /etc/systemd/system/nacos.service
    owner: root
    group: root
    mode: u=rwx,g=r,o=r

- name: Install Nacos - Start nacos and onboot start
  ansible.builtin.systemd:
    name: nacos
    state: started
    enabled: yes
    daemon_reload: yes

# - name: Install Nacos - Load all dataid 
#   block:
#   - name: Login to nacos
#     ansible.builtin.uri:
#       url: http://
#       method: POST
#       body_format: form-urlencoded
#       body:
#         name: your_username
#         password: your_password
#         enter: Sign in
#       status_code: 302
#     register: login
