---
- name: Install Nacos - Install JDK
  ansible.builtin.include: java.yml
  when: java_install

- name: Inatall Nacos - Install unzip
  yum:
    name: unzip
    state: "present"
    update_cache: yes
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Anolis OS' or ansible_os_family == 'OracleLinux'


- name: Install Nacos - unzip Nacos zip
  ansible.builtin.unarchive:
    src: "{{packages_dir}}/{{nacos_package}}"
    dest: "{{nacos_home}}/"
    #remote_src: yes

- name: Install Nacos - Start Nacos
  ansible.builtin.command: sh {{nacos_home}}/nacos/bin/startup.sh -m standalone