---
- name: Install Nacos - Install JDK
  ansible.builtin.include: java.yml
  when: java_install

- name: Install Nacos - unzip Nacos zip
  ansible.builtin.unarchive:
    src: "{{packages_dir}}/{{nacos_package}}"
    dest: "{{nacos_home}}/"
    #remote_src: yes

- name: Install Nacos - Start Nacos
  ansible.builtin.command: sh {{nacos_home}}/nacos/bin/startup.sh -m standalone