---
#----------------------------------mysqltools全局配置文件---------------------
# section 1 #mysqltools所在的目录
mtls_base_dir: /Users/jianglexing/github/mysqltools/
#           #mysqltool自带的各类软件的安装文件所在路径(相对路径)
mtls_packages: deploy/packages/
#           #mysqltool自带的python脚本、下发到被控主机时所保存的路径
mtls_client_base_dir: /usr/local/


#  section 2  #mysqltools自带的各类软件安装文件 的全名、设置这些变量的作用是方便版本共存、mysql不在这里设置是因为
#             #mysql的安装包太大了，mysqltools并没有把它打包进来         
mtls_apr: apr-1.6.2.tar.gz
mtls_apr_util: apr-util-1.6.0.tar.gz
mtls_httpd: httpd-2.4.28.tar.gz
mtls_php: php-5.6.31.tar.gz
#mtls_zabbix: zabbix-3.4.3.tar.gz
mtls_zabbix: zabbix-4.0.0.tar.gz
mtls_python: python-3.6.2.tar.xz
mtls_mysql_connector_python: mysql_connector_python-8.0.12-cp36-cp36m-manylinux1_x86_64.whl
mtls_mycat: mycat-server-1.6.5-linux.tar.gz
mtls_mha_node: mhanode.tar.gz
mtls_mha_manager: mhamanager.tar.gz
mtls_git: git-2.9.5.tar.gz
mtls_nginx: nginx-1.13.7.tar.gz
mtls_sysbench: sysbench-1.1.0.tar.gz
mtls_meb: meb-4.1.0-linux-glibc2.5-x86-64bit.tar.gz
mtls_xtrb: percona-xtrabackup-2.4.9-Linux-x86_64.tar.gz
mtls_mysqlclient: mysqlclient-1.3.12.tar.gz
mtls_pytz: pytz-2018.4.tar.gz
mtls_django: django-2.0.4.tar.gz
mtls_uwsgi: uwsgi-2.0.17.tar.gz

#mysql与php-5.6.x 是否要同时安装在一台主机上、如果是就要把这个设置成yes、以为php导出mysqclient_r.so文件
mtls_with_php: 1
#通过ansible在被控机上安装python-3.x的时候，是否自动安装好mysql-connector-python
mtls_with_mysql_conntor_python: 1
#是否给mysql用户加密码
mtls_make_mysql_secure: 1
#
mtls_with_mysql_group_replication: 0
#----------------------------------mysqltools全局配置文件---------------------


####
#### mysql 相关的配置
####
#mysql 安装包所在的目录
mysql_packages_dir: /root/Softwares/mysql/
#mysql 安装包的名字
#mysql_package: mysql-5.6.44-linux-glibc2.12-x86_64.tar.gz
#mysql_package: mysql-5.7.26-linux-glibc2.12-x86_64.tar.gz
mysql_package: mysql-8.0.16-linux-glibc2.12-x86_64.tar.xz
#linux 系统级别mysql用户相关信息
mysql_user: mysql
mysql_group: mysql
mysql_user_uid: 3306
mysql_user_gid: 3306
#mysql 安装目录
mysql_base_dir: /usr/local/mysql/
#mysql 真正的datadir就会是mysql_data_dir_base+mysql_port
mysql_data_dir_base: /glzt/mysql/data/
mysql_port: 3306
mysql_root_password: mtls0352
mysql_zabbix_password: mtls
mysql_rple_user: repl
mysql_rple_password: repl0352
mysql_mha_user: mha
mysql_mha_password: mtls0352
mysql_app_user: appuser
mysql_app_password: mtls0352
mysql_monitor_user: monitor
mysql_monitor_password: monitor0352
mysql_backup_user: backup
mysql_backup_password: DX3906
#mysql 配置文件模版
mysql_binlog_format: row
mysql_innodb_log_files_in_group: 16
mysql_innodb_log_file_size: 256M
mysql_innodb_log_buffer_size: 64M
mysql_innodb_open_files: 65535
mysql_max_connections: 1000
mysql_thread_cache_size: 256
mysql_sync_binlog: 1
mysql_binlog_cache_size: 64K
mysql_innodb_online_alter_log_max_size: 128M
mysql_performance_schema: 'on'
use_write_set: 1

#mysql 

####
#### zabbix 相关的配置
#####
zabbix_server_ip: 172.16.192.100 

