---
galaxy_info:
  role_name: oraswgi_golden_image
  author: Thorsten Bruhns
  description: Create Golden-Images from Oracle Restart Homes
  company: Thorsten Bruhns

  license: license (MIT)

  min_ansible_version: 2.9.0

  platforms:
    - name: EL
      versions:
        - "6"
        - "7"
        - "8"

  galaxy_tags:
    - database
    - oracle

dependencies:
  - role: orasw_meta
