---
- name: Install Nginx - Install dependency
  ansible.builtin.yum: 
    name: "{{ common_packages }}" 
    state: installed

- name: Install Nginx - Copy Nginx source code
  ansible.builtin.copy:
    src: "{{packages_dir}}/{{nginx_package}}.tar.gz"
    dest: /root/{{nginx_package}}.tar.gz
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Install Nginx - Copy Nginx install shell
  ansible.builtin.template:
    src: install_nginx.sh.j2
    dest: /root/install_nginx.sh
    owner: root
    group: root
    mode: u=rx,g=r,o=r

- name: Install Nginx - Execute install shell
  ansible.builtin.command: /root/install_nginx.sh

- name: Install Nginx - Copy nginx.service
  ansible.builtin.template:
    src: nginx.service.j2
    dest: /etc/systemd/system/nginx.service
    owner: root
    group: root
    mode: u=rwx,g=r,o=r

- name: Install Nginx - Copy api.conf
  ansible.builtin.template:
    src: api.conf.j2
    dest: "{{nginx_home}}/conf.d/api.conf"
    owner: root
    group: root
    mode: u=rwx,g=r,o=r

- name: Install Nginx - Start and Enable Nginx and Just force systemd to reload configs
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
    daemon_reload: yes

# - name: Install Nginx - Start and Enable Nginx
#   ansible.builtin.service:
#     name: nginx
#     state: started
#     enabled: yes

