---
# defaults file for oradb-services

oracle_user: oracle
configure_cluster: false
oracle_base: /u01/app/oracle

default_dbpass: "{% if item.0 is defined and item.0.oracle_db_passwd is defined %}{{ item.0.oracle_db_passwd }}{% else %}Oracle123{% endif %}"
db_user: system
db_password_cdb: "{% if dbpasswords is defined and dbpasswords[item.0.oracle_db_name] is defined and dbpasswords[item.0.oracle_db_name][db_user] is defined%}{{ dbpasswords[item.0.oracle_db_name][db_user] }}
                  {%- else %}{{ default_dbpass }}
                  {%- endif %}"
# noqa yaml

db_password_pdb: "{% if dbpasswords is defined and dbpasswords[item.0.cdb] is defined and dbpasswords[item.0.cdb][db_user] is defined %}{{ dbpasswords[item.0.cdb][db_user] }}
                  {%- else %}{{ default_dbpass }}
                  {%- endif %}"
# noqa yaml

db_service_name: "{% if item.0 is defined %}
                    {%- if item.0.oracle_db_unique_name is defined %}{{ item.0.oracle_db_unique_name }}
                    {%- elif item.0.oracle_db_instance_name is defined %}{{ item.0.oracle_db_instance_name }}
                    {%- else %}{{ item.0.oracle_db_name }}
                    {%- endif %}
                  {%- endif %}"

listener_port_template: "{% if item.0.listener_port is defined %}{{ item.0.listener_port }}{% else %}{{ listener_port }}{% endif %}"
listener_port: 1521

oracle_env:
  ORACLE_HOME: "{{ oracle_home_db }}"
  LD_LIBRARY_PATH: "{{ oracle_home_db }}/lib"


oracle_databases: []
#        - home: db1
#          oracle_db_name: orclcdb
#          services:
#                 - { name: appuser1_service, state: present }
oracle_pdbs: []
#         - pdb_name: orclpdb
#           cdb: orclcdb
#           services:
#                  - { name: appuser2_service, state: present }
