---
- name: Host configuration
  hosts: "{{ hostgroup | default('all') }}"
  become: true
  any_errors_fatal: true
  roles:
    - common
    - orahost
    - orahost_storage
    - orahost_ssh
    - cxoracle
    - orahost_logrotate

  post_tasks:
    - name: Restart autofs
      ansible.builtin.service: 
        name: autofs
        enabled: yes 
        state: restarted
      tags: autofs
