---
vg_name: glzt
pvs_list: /dev/sdb # If, for example, we already have VG vg.services on top of /dev/sdb, this VG will be extended by /dev/sdc.
lv_name: data
mount_point: 
  src: /dev/{{ vg_name }}/{{ lv_name }}
  path: /glzt/
  fstype: xfs
